runtime: java11

instance_class: F1

inbound_services:
  - mail
  - warmup

service: clockin-backend-app

env_variables:
  ALLOWED_ACCOUNT: "@allowed.account@"
  ALLOWED_SENDER_LIST: "@allowed.sender.list@"
